[package]
name = "xenvox"
version = "0.1.0"
authors = ["Сухарик <suhr@i2pmail.org>"]

[dependencies]
gfx = "0.17"
gfx_device_gl = "*"
gfx_window_glutin = "*"
glutin = "*"
cgmath = "*"
rosc = "0.1"

[dependencies.miosc]
path = "../miosc"
